export const FONTS = {
  Inter18Black: "Inter_18pt-Black",
  Inter18BlackItalic: "Inter_18pt-BlackItalic",
  Inter18Bold: "Inter_18pt-Bold",
  PoppinsBlack: "Poppins-Black",
  PoppinsBlackItalics: "Poppins-BlackItalic",
  PoppinsBold: "Poppins-Bold",
  PoppinsBoldItalics: "Poppins-BoldItalic",
  PoppinsExtraBold: "Poppins-ExtraBold",
  PoppinsExtraBoldItalics: "Poppins-ExtraBoldItalic",
  PoppinsExtraLight: "Poppins-ExtraLight",
  PoppinsExtraLightItalics: "Poppins-ExtraLightItalic",
  PoppinsItalic: "Poppins-Italic",
  PoppinsLight: "Poppins-Light",
  PoppinsLightItalics: "Poppins-LightItalic",
  PoppinsMedium: "Poppins-Medium",
  PoppinsMediumItalics: "Poppins-MediumItalic",
  PoppinsRegular: "Poppins-Regular",
  PoppinsSemiBold: "Poppins-SemiBold",
  PoppinsSemiBoldItalics: "Poppins-SemiBoldItalics",
  PoppinsThin: "Poppins-Thin",
  PoppinsThinItalics: "Poppins-ThinItalic",
};
